@rbacapp_HostAddress = http://localhost:5289

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJNYW5hZ2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InVzZXIzIiwiZXhwIjoxNzAyNjM3OTcwfQ.QGvvBFyYwhh1u6Ea2FhoP99Qr2AvK8sQ4ms06rtPEkI


### setup roles
GET {{rbacapp_HostAddress}}/setuproles
Accept: application/json
Content-Type: application/json

### add role
GET {{rbacapp_HostAddress}}/addrole/user3/role/manager
Accept: application/json
Content-Type: application/json

### register
POST {{rbacapp_HostAddress}}/register
Accept: application/json
Content-Type: application/json

{
  "Email": "user3@email.com",
  "Password": "pass123",
  "Username": "user3",
  "Name": "User 3"
}

### login
POST {{rbacapp_HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
  "Password": "pass123",
  "Username": "user3"
}

###
GET {{rbacapp_HostAddress}}/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{rbacapp_HostAddress}}/manager
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{rbacapp_HostAddress}}/admin
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{rbacapp_HostAddress}}/adminmanager
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###